FROM python:3.10.9-slim

WORKDIR /diploma_app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
ENTRYPOINT ["bash", "entrypoint.sh"]
EXPOSE 8000
CMD ["gunicorn", "todolist.wsgi", "-w", "4", "-b", "0.0.0.0:8000"]