FROM python:3.10.9-slim

WORKDIR /diploma_app
COPY requirements.txt .
RUN apt-get update && apt-get install -y build-essential
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
ENTRYPOINT ["bash", "entrypoint.sh"]
EXPOSE 8000
CMD ["gunicorn", "todolist.wsgi", "-w", "4", "-b", "0.0.0.0:8000"]
